# Application Info
info:
  application:
    name: JobMonitor-Server
    description: Job monitoring service for Infor LN, providing real-time job tracking and status APIs.
    author: Shubham Shinde
    version: v1.0.0

# Server Config
server:
  port: ${JOB_MONITOR_SERVER_PORT:8080}

# Spring Config
spring:
  application:
    name: job-monitor-server
  output:
    ansi:
      enabled: always
  profiles:
    active: sqlite
    thymeleaf:
      cache: true
      encoding: utf-8
      enabled: true
      prefix: classpath:/templates/
      suffix: .html

# Logging
logging:
  pattern:
    console: "[%-5level]\t%d{yyyy-MM-dd HH:mm:ss.SSS}\t[%thread] %logger{0} - %msg%n"

# App Config
mail:
  user: ${MAIL_USER}
  password: ${MAIL_PASSWORD}
