<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.shubham225</groupId>
        <artifactId>job-monitor</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>job-monitor-client</artifactId>
    <packaging>pom</packaging>

    <name>JobMonitor - Client</name>
    <description>Rust based client app to interact with JobMonitor server.</description>

    <developers>
        <developer>
            <id>shubhamshinde225</id>
            <name>Shubham Shinde</name>
            <email>shubhamshinde225@gmail.com</email>
        </developer>
    </developers>

    <profiles>
        <!-- Linux / Mac -->
        <profile>
            <id>unix-build</id>
            <activation>
                <os>
                    <family>unix</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.2.0</version>
                        <executions>
                            <execution>
                                <id>run-build-script</id>
                                <phase>compile</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>bash</executable>
                                    <workingDirectory>${basedir}</workingDirectory>
                                    <arguments>
                                        <argument>${basedir}/build.sh</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Windows -->
        <profile>
            <id>windows-build</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.2.0</version>
                        <executions>
                            <execution>
                                <id>run-build-script</id>
                                <phase>compile</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>cmd</executable>
                                    <workingDirectory>${basedir}</workingDirectory>
                                    <arguments>
                                        <argument>/c</argument>
                                        <argument>${basedir}\build.cmd</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>