export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";

export enum ERPJobStatus {
  FREE = "FREE",
  WAITING = "WAITING",
  RUNNING = "RUNNING",
  CANCELED = "CANCELED",
  RUNTIME_ERROR = "RUNTIME_ERROR",
  IN_QUEUE = "IN_QUEUE",
  BLOCKED = "BLOCKED",
  UNKNOWN = "UNKNOWN"
}

export enum TaskSchedulerStatus {
  READY = "READY",
  RUNNING = "RUNNING",
  DISABLED = "DISABLED",
  QUEUED = "QUEUED",
  UNKNOWN = "UNKNOWN",
  COULD_NOT_START = "COULD_NOT_START",
  HAS_NOT_RUN = "HAS_NOT_RUN",
  IDLE = "IDLE",
  WAITING = "WAITING",
  PAUSED = "PAUSED",
  TERMINATED = "TERMINATED",
  MISSED = "MISSED",
  NO_MORE_RUNS = "NO_MORE_RUNS",
  NOT_SCHEDULED = "NOT_SCHEDULED",
  TRANSITION = "TRANSITION",
  PENDING = "PENDING"
}

export enum FailureReason {
  PENDING = "PENDING",
  JOB_DETAILS_MISSING = "JOB_DETAILS_MISSING",
  NOT_FOUND = "NOT_FOUND",
  NOT_EXECUTED = "NOT_EXECUTED",
  RUNTIME_ERROR = "RUNTIME_ERROR",
  EXECUTED_WITH_RUNTIME_ERROR = "EXECUTED_WITH_RUNTIME_ERROR",
  TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED",
  CANCELED = "CANCELED",
  ERP_API_DOWN = "ERP_API_DOWN",
  EXECUTED = "EXECUTED",
  WIN_SCHEDULER_RUNNING = "WIN_SCHEDULER_RUNNING",
  EXEC_WITH_ERROR_MESSAGE = "EXEC_WITH_ERROR_MESSAGE",
  SKIPPED = "SKIPPED",
}