import { Company } from "./types";

export const companies: Company[] = [
  {
    id: "1",
    name: "Johnson & Johnson",
    logoFallback: "J&J",
    logoColor: "bg-red-500",
    categories: ["B2B", "B2C", "Marketplace", "Technology"],
    lastInteraction: "2 days ago",
    domain: "jnj.com",
    phone: "+7 (848) 960-94-20",
  },
  {
    id: "2",
    name: "Adidas",
    logoFallback: "AD",
    logoColor: "bg-neutral-900",
    categories: ["B2B", "B2C", "Marketplace"],
    lastInteraction: "5 hours ago",
    domain: "adidas.com",
    phone: "+7 (975) 539-46-01",
  },
  {
    id: "3",
    name: "Nike",
    logoFallback: "N",
    logoColor: "bg-neutral-900",
    categories: ["B2B", "B2C", "Marketplace"],
    lastInteraction: "2 days ago",
    domain: "nike.com",
    phone: "+7 (850) 172-61-97",
  },
  {
    id: "4",
    name: "TATA Group",
    logoFallback: "TG",
    logoColor: "bg-blue-700",
    categories: ["B2B", "Marketplace"],
    lastInteraction: "12 days ago",
    domain: "tatagroup.com",
    phone: "+7 (848) 960-94-20",
    assignee: { name: "Khansa", color: "bg-sky-200 text-sky-900" },
  },
  {
    id: "5",
    name: "Apple",
    logoFallback: "",
    logoColor: "bg-neutral-900",
    categories: ["B2B", "Marketplace", "Technology"],
    lastInteraction: "24 hours ago",
    domain: "apple.com",
    phone: "+7 (926) 957-49-97",
  },
  {
    id: "6",
    name: "Google",
    logoFallback: "G",
    logoColor: "bg-white border",
    categories: ["B2B", "B2C", "Marketplace", "Technology"],
    lastInteraction: "5 days ago",
    domain: "google.com",
    phone: "+7 (809) 510-45-80",
  },
  {
    id: "7",
    name: "Starbucks",
    logoFallback: "S",
    logoColor: "bg-green-700",
    categories: ["B2C", "Marketplace", "Technology"],
    lastInteraction: "8 days ago",
    domain: "starbucks.com",
    phone: "+7 (815) 150-60-61",
  },
  {
    id: "8",
    name: "Netflix",
    logoFallback: "N",
    logoColor: "bg-red-600",
    categories: ["B2C", "Technology"],
    lastInteraction: null,
    domain: "netflix.com",
    phone: "+7 (936) 834-82-31",
    assignee: { name: "Albert", color: "bg-fuchsia-200 text-fuchsia-900" },
  },
  {
    id: "9",
    name: "Microsoft",
    logoFallback: "M",
    logoColor: "bg-blue-500",
    categories: ["B2C", "Marketplace", "Technology"],
    lastInteraction: null,
    domain: "microsoft.com",
    phone: "+7 (846) 618-10-05",
  },
  {
    id: "10",
    name: "Dell",
    logoFallback: "DE",
    logoColor: "bg-sky-600",
    categories: ["B2B", "B2C"],
    lastInteraction: null,
    domain: "dellgroup.com",
    phone: "+7 (848) 900-24-28",
  },
  {
    id: "11",
    name: "MCD",
    logoFallback: "M",
    logoColor: "bg-red-500",
    categories: ["B2C", "Marketplace", "Technology"],
    lastInteraction: "2 days ago",
    domain: "macdonald.com",
    phone: "+7 (815) 150-60-61",
  },
  {
    id: "12",
    name: "Tesla",
    logoFallback: "T",
    logoColor: "bg-red-600",
    categories: ["B2B", "B2C", "Marketplace", "Technology"],
    lastInteraction: "2 days ago",
    domain: "tesla.com",
    phone: "+7 (848) 960-94-20",
  },
  {
    id: "13",
    name: "BMW",
    logoFallback: "BM",
    logoColor: "bg-blue-800",
    categories: ["B2B", "B2C", "Technology"],
    lastInteraction: null,
    domain: "bmw.com",
    phone: "+7 (825) 304-66-79",
    assignee: { name: "Lonna", color: "bg-lime-200 text-lime-900" },
  },
  {
    id: "14",
    name: "Burger King",
    logoFallback: "BK",
    logoColor: "bg-orange-500",
    categories: ["B2C", "Marketplace", "Technology"],
    lastInteraction: null,
    domain: "burgerking.com",
    phone: "+7 (825) 304-66-79",
  },
  {
    id: "15",
    name: "IKEA",
    logoFallback: "IK",
    logoColor: "bg-blue-600",
    categories: ["B2C", "Technology"],
    lastInteraction: null,
    domain: "ikea.com",
    phone: "+7 (934) 161-53-89",
  },
  {
    id: "16",
    name: "Pizza Hut",
    logoFallback: "PH",
    logoColor: "bg-red-600",
    categories: ["B2B", "Marketplace"],
    lastInteraction: "1 hours ago",
    domain: "pizzahut.com",
    phone: "+7 (809) 510-45-80",
  },
];
